language: python
python: 2.7
sudo: required
dist: xenial
env:
  - PY=p ANGR_REPO=rex
install: ( curl https://raw.githubusercontent.com/angr/angr-dev/$TRAVIS_BRANCH/travis-install.sh | grep -v 404 || curl https://raw.githubusercontent.com/angr/angr-dev/master/travis-install.sh ) | bash
script: ~/angr-dev/travis-test.sh
